// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWNXfAybwKbGdtWlmoYSTXFoXuA5_vG90',
    appId: '1:555603401792:web:d2bae8a5a1f8fa973d13a5',
    messagingSenderId: '555603401792',
    projectId: 'todo-flutter-app-b23f7',
    authDomain: 'todo-flutter-app-b23f7.firebaseapp.com',
    storageBucket: 'todo-flutter-app-b23f7.firebasestorage.app',
    measurementId: 'G-D88WKHLHXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFqBClHWUYb0GysJEclwhED1I7eC5_mPk',
    appId: '1:555603401792:android:e31572858a4f601b3d13a5',
    messagingSenderId: '555603401792',
    projectId: 'todo-flutter-app-b23f7',
    storageBucket: 'todo-flutter-app-b23f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWsZSEHm7xjbXo1NUQufJG4AQuW7QOVuI',
    appId: '1:555603401792:ios:c0fd1b5b750078573d13a5',
    messagingSenderId: '555603401792',
    projectId: 'todo-flutter-app-b23f7',
    storageBucket: 'todo-flutter-app-b23f7.firebasestorage.app',
    iosBundleId: 'com.example.todoAppTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWsZSEHm7xjbXo1NUQufJG4AQuW7QOVuI',
    appId: '1:555603401792:ios:c0fd1b5b750078573d13a5',
    messagingSenderId: '555603401792',
    projectId: 'todo-flutter-app-b23f7',
    storageBucket: 'todo-flutter-app-b23f7.firebasestorage.app',
    iosBundleId: 'com.example.todoAppTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWNXfAybwKbGdtWlmoYSTXFoXuA5_vG90',
    appId: '1:555603401792:web:98c885a2b9a2fdbb3d13a5',
    messagingSenderId: '555603401792',
    projectId: 'todo-flutter-app-b23f7',
    authDomain: 'todo-flutter-app-b23f7.firebaseapp.com',
    storageBucket: 'todo-flutter-app-b23f7.firebasestorage.app',
    measurementId: 'G-5N8DP86Y8J',
  );
}
